name: dio_project
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  #Client Dio
  dio: ^4.0.6

  #State management
  mobx: ^2.0.6
  flutter_mobx: ^2.0.4


  #Useful Tools
  flutter_dotenv: ^5.0.0
  get_it: ^7.2.0
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  mobx_codegen: ^2.0.5
  
  
  
  
  
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - .env

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
